var path = require('path');
var webpack = require('webpack');
var AppCachePlugin = require('appcache-webpack-plugin');
var autoprefixer = require('autoprefixer');
var precss = require('precss');
var HtmlWebpackPlugin = require('html-webpack-plugin');
// http://stackoverflow.com/questions/33502987/webpack-bundle-js-not-found
// expose
module.exports = {
    entry: [
        'webpack-hot-middleware/client',
        path.resolve(__dirname, '../app/index.js')
    ],
    output: {
        path: path.join(__dirname, '../dist/'),
        filename: 'bundle.js',
        sourceMapFilename: "[file].map"
    },
    plugins: [
        new AppCachePlugin(),
        new webpack.HotModuleReplacementPlugin(), // Make hot loading work
        new HtmlWebpackPlugin({
            template: 'index.html', // Move the index.html file
            //minify: {
            //    minifyJS: true,
            //    minifyCSS: true,
            //    minifyURLs: true
            //},
            inject: true // inject all files that are generated by webpack
        })
    ],
    module: {
        loaders: [
            {
                test: /\.css$/,
                loader: "style-loader!css-loader!postcss-loader"
            },
            {
                test: /\.js$/, // Transform all .js files required somewhere within an entry point
                loader: 'babel',
                exclude: path.join(__dirname, '/node_modules/') // except for the node_modules folder.
            }
        ]
    },
    postcss: function () {
        return [autoprefixer, precss];
    }
}